"""0002-Creacion de tabla de platos

Revision ID: 399593bec3dc
Revises: b1e1d4bba455
Create Date: 2026-07-30 20:12:34.354549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399593bec3dc'
down_revision = 'b1e1d4bba455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platos')
    # ### end Alembic commands ###
