# Generated by Django 6.1 on 2026-08-28 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestauranteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'restaurantes',
            },
        ),
        migrations.CreateModel(
            name='SucursalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=9, null=True)),
                ('foto_url', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='restaurantes.restaurantemodel')),
            ],
            options={
                'db_table': 'sucursales',
                'unique_together': {('restaurante', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='MesaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.CharField(choices=[('salon', 'Salon'), ('terraza', 'Terraza'), ('barra', 'Barra')], default='salon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='restaurantes.sucursalmodel')),
            ],
            options={
                'db_table': 'mesas',
                'unique_together': {('sucursal', 'numero')},
            },
        ),
    ]
