# Generated by Django 6.1 on 2026-08-21 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoriasmodel',
            table='categorias',
        ),
    ]
