"""Agregado de columnas en la tabla platos

Revision ID: 114ac7454a1f
Revises: 48a5e9615648
Create Date: 2026-07-24 22:00:58.261375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114ac7454a1f'
down_revision = '48a5e9615648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platos', schema=None) as batch_op:
        batch_op.drop_column('precio')
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
