"""Elimnacion de columnas en la tabla platos

Revision ID: 48a5e9615648
Revises: cd2e99681326
Create Date: 2026-07-24 21:58:30.497871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a5e9615648'
down_revision = 'cd2e99681326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platos', schema=None) as batch_op:
        batch_op.drop_column('categoria')
        batch_op.drop_column('precio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
