"""Migracion inicial

Revision ID: cc673ea487bb
Revises: 
Create Date: 2026-07-24 21:49:50.987629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc673ea487bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=9), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
